# Generated by Django 4.0 on 2022-06-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_blocked_kick',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_forced_fum',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_fum_rec',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_int',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_pa_0',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_pa_13',
            field=models.DecimalField(decimal_places=3, default=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_pa_27',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_pa_34',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_pa_35_plus',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_pa_6',
            field=models.DecimalField(decimal_places=3, default=7, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_sack',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_saftey',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='def_td',
            field=models.DecimalField(decimal_places=3, default=6, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='fg_0_19',
            field=models.DecimalField(decimal_places=3, default=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='fg_20_29',
            field=models.DecimalField(decimal_places=3, default=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='fg_30_39',
            field=models.DecimalField(decimal_places=3, default=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='fg_40_49',
            field=models.DecimalField(decimal_places=3, default=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='fg_50_plus',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='fg_miss',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='fumble',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='fumble_lost',
            field=models.DecimalField(decimal_places=3, default=-2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='pass_2pts',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='pass_ints',
            field=models.DecimalField(decimal_places=3, default=-2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='pass_tds',
            field=models.DecimalField(decimal_places=3, default=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='pass_yds',
            field=models.DecimalField(decimal_places=3, default=0.04, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='ppr',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='rec_2pts',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='rec_prem_rb',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='rec_prem_te',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='rec_prem_wr',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='rec_tds',
            field=models.DecimalField(decimal_places=3, default=6, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='rec_yds',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='rush_2pts',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='rush_tds',
            field=models.DecimalField(decimal_places=3, default=6, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='rush_yds',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='xp_made',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scoringsettings',
            name='xp_miss',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=6),
        ),
    ]
