# Generated by Django 4.0 on 2022-06-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0003_alter_playerprojections_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprojections',
            name='fp_est',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
