# Generated by Django 4.0 on 2022-09-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0003_rename_rec_prem_rb_scoringsettings_blk_kick_ret_yd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringsettings',
            name='bonus_rec_rec_yd_100',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
