# Generated by Django 4.0 on 2022-09-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0004_scoringsettings_bonus_rec_rec_yd_100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringsettings',
            old_name='bonus_rec_rec_yd_100',
            new_name='bonus_rush_rec_yd_100',
        ),
    ]
