# Generated by Django 4.0 on 2022-09-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0005_rename_bonus_rec_rec_yd_100_scoringsettings_bonus_rush_rec_yd_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringsettings',
            name='pass_td_40p',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
