# Generated by Django 4.0 on 2022-09-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0006_scoringsettings_pass_td_40p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringsettings',
            old_name='idk_tkl_solo',
            new_name='bonus_def_fum_td_50p',
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='bonus_rec_yd_100',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='bonus_sack_2p',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='def_2pt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='def_st_fum_rec',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='idp_fum_ret_yd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='idp_tkl_solo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='qb_hit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='rush_fd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='safe',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='tkl_ast',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='tkl_solo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='yds_allow',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='scoringsettings',
            name='yds_allow_200_299',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
