# Generated by Django 4.0 on 2022-09-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0008_fantasyleague_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyleague',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
