# Generated by Django 4.0 on 2022-10-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0009_alter_fantasyleague_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprojections',
            old_name='def_forced_fum',
            new_name='def_2pt',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='def_fum_rec',
            new_name='fgm',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='def_pa',
            new_name='fgm_0_19',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='def_sack',
            new_name='fgm_20_29',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='def_saftey',
            new_name='fgm_30_39',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='def_total',
            new_name='fgm_40_49',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='def_yds_against',
            new_name='fgm_50p',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='fg',
            new_name='fum',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='fumbles',
            new_name='fum_rec',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='k_total',
            new_name='pts_allow',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='rec_rec',
            new_name='rec',
        ),
        migrations.RenameField(
            model_name='playerprojections',
            old_name='total',
            new_name='sack',
        ),
        migrations.AddField(
            model_name='playerprojections',
            name='safe',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
