# Generated by Django 4.0 on 2022-04-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='status',
            field=models.CharField(max_length=60),
        ),
    ]
