# Generated by Django 4.0 on 2022-06-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettingleague',
            name='weekly_allowance',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
