# Generated by Django 4.0 on 2022-04-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('Betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyteam',
            name='userAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Account.user'),
        ),
        migrations.AlterField(
            model_name='league',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='Account.user'),
        ),
    ]
