# Generated by Django 4.0 on 2022-06-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0001_initial'),
        ('Betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupbets',
            name='betting_league',
            field=models.ForeignKey(default='8bc5802f-402b-4ab1-a486-e7487936aa2c', on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='Betting.bettingleague'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchupbets',
            name='fantasy_matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betting_matchups', to='Fantasy.matchup'),
        ),
    ]
