# Generated by Django 4.0 on 2022-06-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchupbets',
            old_name='over_line',
            new_name='over_odds',
        ),
        migrations.RenameField(
            model_name='matchupbets',
            old_name='spread_team1_line',
            new_name='spread_team1_odds',
        ),
        migrations.RenameField(
            model_name='matchupbets',
            old_name='spread_team2_line',
            new_name='spread_team2_odds',
        ),
        migrations.RenameField(
            model_name='matchupbets',
            old_name='under_line',
            new_name='under_odds',
        ),
    ]
