# Generated by Django 4.0 on 2022-06-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedmatchupbet',
            old_name='id_placed',
            new_name='id',
        ),
    ]
