# Generated by Django 4.0 on 2022-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0002_rename_id_placed_placedmatchupbet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedmatchupbet',
            name='parlayed',
            field=models.BooleanField(default=False),
        ),
    ]
