# Generated by Django 4.0 on 2022-06-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0002_alter_bettingleague_weekly_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettor',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
