# Generated by Django 4.0 on 2022-06-29 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0002_matchupbets_betting_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupbets',
            name='payout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 3, 0)),
        ),
    ]
