# Generated by Django 4.0 on 2022-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0002_alter_league_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='ppr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='league',
            name='tePremium',
            field=models.IntegerField(),
        ),
    ]
