# Generated by Django 4.0 on 2022-04-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0003_alter_league_ppr_alter_league_tepremium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='ppr',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='league',
            name='tePremium',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='player',
            name='currentProj',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
