# Generated by Django 4.0 on 2022-06-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0003_placedmatchupbet_parlayed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedmatchupbet',
            old_name='mathcup',
            new_name='matchup',
        ),
    ]
