# Generated by Django 4.0 on 2022-06-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0003_bettor_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettor',
            name='is_email_verified',
        ),
    ]
