# Generated by Django 4.0 on 2022-04-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0004_alter_league_ppr_alter_league_tepremium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nflTeam',
            field=models.CharField(choices=[('BUF', 'Buffalo Bills'), ('MIA', 'Miami Dolphins'), ('NE', 'New England Patriots'), ('NYJ', 'New York Jets'), ('BAL', 'Baltimore Ravens'), ('CIN', 'Cincinnati Bengals'), ('CLE', 'Cleveland Browns'), ('PIT', 'Pittsburgh Steelers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('TEN', 'Tennessee Titans'), ('DEN', 'Denver Broncos'), ('KC', 'Kansas City Chiefs'), ('LV', 'Las Vegas Raiders'), ('LAC', 'Los Angeles Chargers'), ('DAL', 'Dallas Cowboys'), ('NYG', 'New York Giants'), ('PHI', 'Philadelphia Eagles'), ('WAS', 'Washington Commanders'), ('CHI', 'Chicago Bears'), ('DET', 'Detriot Lions'), ('GB', 'Green Bay Packers'), ('MIN', 'Minnesota Vikings'), ('ATL', 'Atlanta Falcons'), ('CAR', 'Carolina Panthers'), ('NO', 'New Orleans Saints'), ('TB', 'Tamba Bay Buccaneers'), ('ARI', 'Arizona Cardinals'), ('LAR', 'Los Angeles Rams'), ('SF', 'San Francisco 49ers'), ('SEA', 'Seattle Seahawks'), ('FREE', 'Free Agent')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pos',
            field=models.CharField(choices=[(1, 'Quarterback'), (2, 'Runningback'), (3, 'Wide Reciever'), (4, 'Tight End'), (5, 'Kicker'), (6, 'Defense and Special Teams')], max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='pos2',
            field=models.CharField(choices=[(1, 'Quarterback'), (2, 'Runningback'), (3, 'Wide Reciever'), (4, 'Tight End'), (5, 'Kicker'), (6, 'Defense and Special Teams')], max_length=5, null=True),
        ),
    ]
