# Generated by Django 4.0 on 2022-07-09 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0004_rename_mathcup_placedmatchupbet_matchup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedBet',
            fields=[
                ('betStatus', models.CharField(choices=[('O', 'Open'), ('W', 'Won'), ('L', 'Lost'), ('R', 'Refunded'), ('C', 'Cashed Out')], default='O', max_length=64)),
                ('line', models.DecimalField(decimal_places=3, max_digits=9)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_placed', models.DateTimeField()),
                ('payout_date', models.DateTimeField()),
                ('parlayed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subtype', models.CharField(choices=[('FFM', 'Fantasy Football Matchup')], max_length=64)),
                ('bet_type', models.CharField(choices=[('M_O', 'Over'), ('M_U', 'Under'), ('M_M1', 'Moneyline Team1'), ('M_M2', 'Moneyline Team2'), ('M_S1', 'Spread Team1'), ('M_S2', 'Spread Team2')], max_length=20)),
                ('bet_value', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bettor',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bettor',
            name='bets_left',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='matchupbets',
            name='payout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 7, 0, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='PlacedMatchupBet',
        ),
        migrations.AddField(
            model_name='placedbet',
            name='bettor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Betting.bettor'),
        ),
        migrations.AddField(
            model_name='placedbet',
            name='matchup_bet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Betting.matchupbets'),
        ),
    ]
