# Generated by Django 4.0 on 2022-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0005_alter_player_nflteam_alter_player_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nflTeam',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pos',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='pos2',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
