# Generated by Django 4.0 on 2022-07-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0005_placedbet_alter_bettor_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedparlay',
            name='placed_bets',
            field=models.ManyToManyField(to='Betting.PlacedBet'),
        ),
    ]
