# Generated by Django 4.0 on 2022-07-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0006_placedparlay_placed_bets'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedparlay',
            name='wager',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placedparlay',
            name='betStatus',
            field=models.CharField(choices=[('O', 'Open'), ('W', 'Won'), ('L', 'Lost'), ('R', 'Refunded'), ('C', 'Cashed Out')], default='O', max_length=64),
        ),
    ]
