# Generated by Django 4.0 on 2022-07-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0007_placedparlay_wager_alter_placedparlay_betstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedparlay',
            old_name='payoutDate',
            new_name='payout_date',
        ),
    ]
