# Generated by Django 4.0 on 2022-04-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0007_alter_player_nflteam_alter_player_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='fpts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='rosterId',
            field=models.IntegerField(null=True),
        ),
    ]
