# Generated by Django 4.0 on 2022-07-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0008_rename_payoutdate_placedparlay_payout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedparlay',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
