# Generated by Django 4.0 on 2022-04-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0008_fantasyteam_fpts_fantasyteam_rosterid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fantasyteam',
            old_name='loss',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='fantasyteam',
            old_name='tie',
            new_name='ties',
        ),
        migrations.RenameField(
            model_name='fantasyteam',
            old_name='win',
            new_name='wins',
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='funName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='sleeperName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
