# Generated by Django 4.0 on 2022-04-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0009_rename_loss_fantasyteam_losses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyteam',
            name='sleeperId',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
