# Generated by Django 4.0 on 2022-04-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0010_alter_fantasyteam_sleeperid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyteam',
            name='matchupId',
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='currentMathcupId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='currentProj',
            field=models.FloatField(null=True),
        ),
    ]
