# Generated by Django 4.0 on 2022-07-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0010_bettingleague_parlay_vig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedbet',
            old_name='betStatus',
            new_name='bet_status',
        ),
    ]
