# Generated by Django 4.0 on 2022-07-19 01:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0011_rename_betstatus_placedbet_bet_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedparlay',
            old_name='betStatus',
            new_name='bet_status',
        ),
        migrations.AlterField(
            model_name='matchupbets',
            name='payout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 7, 0, tzinfo=utc)),
        ),
    ]
