# Generated by Django 4.0 on 2022-04-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0011_remove_fantasyteam_matchupid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='currentProj',
        ),
        migrations.AddField(
            model_name='player',
            name='currentFumbles',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='currentInts',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='currentPassingTds',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='currentPassingYds',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='currentRushingTds',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='currentRushingYds',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='projFumbles',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='projInts',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='projPassingTds',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='projPassingYds',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='projRushingTds',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='projRushingYds',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
