# Generated by Django 4.0 on 2022-09-15 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0012_rename_betstatus_placedparlay_bet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingleague',
            name='league_name',
            field=models.CharField(default='test league 1', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchupbets',
            name='payout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 7, 0, tzinfo=utc)),
        ),
    ]
