# Generated by Django 4.0 on 2022-04-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0013_alter_player_projfumbles_alter_player_projints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='projFumbles',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='projInts',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='projPassingTds',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='projPassingYds',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='projRushingTds',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='projRushingYds',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
