# Generated by Django 4.0 on 2022-09-23 19:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0001_initial'),
        ('Account', '0003_alter_user_is_email_verified'),
        ('Betting', '0013_bettingleague_league_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchupbets',
            name='payout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 7, 0, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='JoinRequests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='OPEN', max_length=10)),
                ('request_date', models.DateField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Betting.bettingleague')),
                ('request_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fantasy.fantasyteam')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.user')),
            ],
        ),
    ]
