# Generated by Django 4.0 on 2022-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0014_alter_matchupbets_payout_date_joinrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequests',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
