# Generated by Django 4.0 on 2022-04-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0014_alter_player_projfumbles_alter_player_projints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currentRec',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='currentRecTds',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='currentRecYds',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='projRec',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='projRecTds',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='projRecYds',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
