# Generated by Django 4.0 on 2022-09-28 01:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_user_is_email_verified'),
        ('Betting', '0015_alter_joinrequests_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingleague',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bettingleague',
            name='bookie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookie', to='Account.user'),
        ),
    ]
