# Generated by Django 4.0 on 2022-09-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0016_bettingleague_last_update_alter_bettingleague_bookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettingleague',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
