# Generated by Django 4.0 on 2022-04-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0017_player_currentdints_player_currentdtds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='projxpt',
            new_name='projXpt',
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='currentProj',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
    ]
