# Generated by Django 4.0 on 2022-10-01 00:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0010_rename_def_forced_fum_playerprojections_def_2pt_and_more'),
        ('Betting', '0017_alter_bettingleague_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchupbets',
            name='fantasy_matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betting_matchup', to='Fantasy.matchup'),
        ),
        migrations.AlterField(
            model_name='matchupbets',
            name='payout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 7, 0, tzinfo=utc)),
        ),
    ]
