# Generated by Django 4.0 on 2022-05-02 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0018_rename_projxpt_player_projxpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='rbPremium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='league',
            name='wrPremium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='FantasyTeams', to='Betting.league'),
        ),
        migrations.AlterField(
            model_name='league',
            name='ppr',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='league',
            name='tePremium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
