# Generated by Django 4.0 on 2022-05-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0019_league_rbpremium_league_wrpremium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='estProj',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
