# Generated by Django 4.0 on 2022-05-02 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_password'),
        ('Betting', '0021_league_freeagents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bettor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasyTeams', models.ManyToManyField(to='Betting.FantasyTeam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betStatus', models.CharField(choices=[('O', 'Open'), ('W', 'Won'), ('L', 'Lost'), ('R', 'Refunded'), ('C', 'Cashed Out')], max_length=64)),
                ('betType', models.CharField(choices=[('ML', 'Moneyline'), ('OU', 'Over Under'), ('SP', 'Spread')], max_length=64)),
                ('betValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('betAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week', models.IntegerField()),
                ('bettor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Betting.bettor')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bettingTeam1', to='Betting.fantasyteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bettingTeam2', to='Betting.fantasyteam')),
            ],
        ),
    ]
