# Generated by Django 4.0 on 2022-05-02 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0022_bettor_bets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bets',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='bets',
            name='team2',
        ),
        migrations.AddField(
            model_name='bets',
            name='teamToLose',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='teamToLose', to='Betting.fantasyteam'),
        ),
        migrations.AddField(
            model_name='bets',
            name='teamToWin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='teamToWin', to='Betting.fantasyteam'),
        ),
    ]
