# Generated by Django 4.0 on 2022-05-02 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0023_remove_bets_team1_remove_bets_team2_bets_teamtolose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bets',
            name='betValue',
        ),
        migrations.RemoveField(
            model_name='bets',
            name='teamToLose',
        ),
        migrations.AddField(
            model_name='bets',
            name='vig',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bettor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='standardVig',
            field=models.DecimalField(decimal_places=4, default=0.075, max_digits=7),
        ),
        migrations.AlterField(
            model_name='bets',
            name='teamToWin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teamToWin', to='Betting.fantasyteam'),
        ),
        migrations.RemoveField(
            model_name='bettor',
            name='fantasyTeams',
        ),
        migrations.AddField(
            model_name='bettor',
            name='fantasyTeams',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Betting.fantasyteam'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchupId', models.IntegerField()),
                ('over_under', models.DecimalField(decimal_places=3, max_digits=8)),
                ('t1_ML', models.DecimalField(decimal_places=3, max_digits=8)),
                ('t2_ML', models.DecimalField(decimal_places=3, max_digits=8)),
                ('t1_SP', models.DecimalField(decimal_places=3, max_digits=8)),
                ('t2_SP', models.DecimalField(decimal_places=3, max_digits=8)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchupTeam1', to='Betting.fantasyteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchupTeam2', to='Betting.fantasyteam')),
            ],
        ),
        migrations.AddField(
            model_name='bets',
            name='matchup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Betting.matchup'),
            preserve_default=False,
        ),
    ]
