# Generated by Django 4.0 on 2022-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0024_remove_bets_betvalue_remove_bets_teamtolose_bets_vig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bets',
            name='week',
        ),
        migrations.AddField(
            model_name='matchup',
            name='season',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchup',
            name='t1_finalScore',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchup',
            name='t1_projection',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchup',
            name='t2_finalScore',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchup',
            name='t2_projection',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchup',
            name='week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nflstate',
            name='non_reg_week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
