# Generated by Django 4.0 on 2022-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0025_remove_bets_week_matchup_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflstate',
            name='lastPlayerUpdate',
            field=models.DateTimeField(null=True),
        ),
    ]
