# Generated by Django 4.0 on 2022-05-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0029_alter_bettor_balance_alter_matchup_t1_finalscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='vig',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='FantasyTeam', to='Betting.league'),
        ),
    ]
