# Generated by Django 4.0 on 2022-05-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0030_matchup_vig_alter_fantasyteam_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='payoutDate',
            field=models.DateTimeField(null=True),
        ),
    ]
