# Generated by Django 4.0 on 2022-05-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0031_matchup_payoutdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchup',
            old_name='vig',
            new_name='standardLine',
        ),
    ]
