# Generated by Django 4.0 on 2022-05-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0032_rename_vig_matchup_standardline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchupBets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betStatus', models.CharField(choices=[('O', 'Open'), ('W', 'Won'), ('L', 'Lost'), ('R', 'Refunded'), ('C', 'Cashed Out')], max_length=64)),
                ('betType', models.CharField(choices=[('ML', 'Moneyline'), ('OU', 'Over Under'), ('SP', 'Spread')], max_length=64)),
                ('betAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line', models.DecimalField(decimal_places=4, max_digits=7)),
                ('payoutDate', models.DateTimeField()),
                ('bettor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Betting.bettor')),
            ],
        ),
        migrations.CreateModel(
            name='Parlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betStatus', models.CharField(choices=[('O', 'Open'), ('W', 'Won'), ('L', 'Lost'), ('R', 'Refunded'), ('C', 'Cashed Out')], max_length=64)),
                ('line', models.DecimalField(decimal_places=4, max_digits=7)),
                ('payoutDate', models.DateTimeField()),
                ('bets', models.ManyToManyField(to='Betting.MatchupBets')),
                ('bettor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Betting.bettor')),
            ],
        ),
        migrations.AddField(
            model_name='matchup',
            name='vig',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bets',
        ),
        migrations.AddField(
            model_name='matchupbets',
            name='matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Betting.matchup'),
        ),
        migrations.AddField(
            model_name='matchupbets',
            name='teamToWin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teamToWin', to='Betting.fantasyteam'),
        ),
    ]
