# Generated by Django 4.0 on 2022-05-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0033_matchupbets_parlay_matchup_vig_delete_bets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='vig',
        ),
    ]
