# Generated by Django 4.0 on 2022-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0034_remove_matchup_vig'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='vig',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
