# Generated by Django 4.0 on 2022-06-02 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0035_matchup_vig'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettor',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Betting.league'),
        ),
    ]
