# Generated by Django 4.0 on 2022-06-02 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Betting', '0036_bettor_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyteam',
            name='bettor',
        ),
        migrations.AddField(
            model_name='bettor',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Betting.fantasyteam'),
        ),
    ]
